# Generated by Django 3.0.3 on 2020-02-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200215_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='username',
            field=models.CharField(default='Admin', max_length=100),
            preserve_default=False,
        ),
    ]
